### ISSUE TITLE
itn1_stuckrestart doesn't work when lastblockDate is low

### ISSUE THREAD

**Issue by cardano-stake-and-relax** [gacallea/itn1_cluster#2] opened 2020-04-19 00:21 UTC
Cause of the way lastBlockDate and nowBlockDate are compared. itn1_stuckrestart doesn't restart the node when lastBLockDate is very low.

See the following example and suggestion:

```
`#!/bin/bash
#### Setting variables for test

nowBlockDate=127.3000
lastBlockDate=127.1
maxBlockDelta=3000
slot=3000
slotlast=($(echo "$lastBlockDate" | awk -F. '{print $2}'))

### Test if node is stuck

slotdiff=($(echo "$slot - $slotlast" | bc))
deltaBlockCount=$(echo "$nowBlockDate" - "$lastBlockDate" | bc | sed 's/0//g' | sed 's/\.//g')

echo "The varianble deltaBlockCount gives $deltaBlockCount"

if [ "$slotdiff" -gt "$deltaBlockCount" ] ; then
	deltaBlockCount="$slotdiff"
fi
echo "$deltaBlockCount"

if [ "$deltaBlockCount" -ge "$maxBlockDelta" ] ; then
	echo "Node is stuck"
fi

```

**Comment by gacallea** [comment] 2020-04-23 08:49
Hi,

thank you for opening this issue and apologies for the late reply.

That is very much by design. the high threshold is set to "100 slots" and "300 seconds" on purpose, so that it is only restarted when being stuck for some time. If you wish to lower the thresholds you can change the variables values at the top of the script:

```
## CHANGE TO WHAT SUITS YOU THE BEST
maxBlockDelta=100 ## slots
maxDateDelta=300  ## seconds
```

You will also need to run this script from the systemd timer instead, and disable the cronjob, so that by running it more frequently the checks will not incur in issues derived by high frequency/lower thresholds.

I hope this makes sense to you.

Cheers

**Comment by gacallea** [comment] 2020-04-25 08:55
closing this issue since it's possible to lower the thresholds to achieve lower values/higher frequency checks without changes. feel free to comment and re-open if not solved in your opinion.

**Closed by gacallea** 2020-04-25 08:55 UTC
