### ISSUE TITLE
Stuck restart script not triggered

### ISSUE THREAD

**Issue by node-networks-crypto** [gacallea/itn1_cluster#3] opened 2020-05-22 02:09 UTC
I found a case where my node had lagged behind the tip but was still 'running'.  I was away for approximately 10 hours so I'm not sure what caused the syncing issue. 
 Testing with `nowBlockDate=158.37000` and `lastBlockDate=158.9000`, the restart script wasn't triggering.  Upon further investigation, the current method was returning a negative number for `deltaBlockCount` not triggering the case `[ "$deltaBlockCount" -ge "$maxBlockDelta" ].`  I have adjusted how that case is calculated although a little verbose:

`nowBlockDate=$(echo $nowBlockDate | sed 's/\.//g')
lastBlockDate=$(echo $lastBlockDate | sed 's/\.//g')
deltaBlockCount=$(echo "$nowBlockDate - $lastBlockDate" | bc)`

This returns a positive number and if the restart threshold is high enough, will work across epochs!

**Comment by gacallea** [comment] 2020-05-22 11:01
hi @node-networks-crypto ,

thanks for your feedback, I appreciate.

You are right, future block returns a negative delta. Because the delta check only triggers when it more than X, the restart won't trigger. I'm aware of that and other users have contacted me in the past. I left in place like so, and it is very much by design.

Why does the future block happen? Because sometime your nodes are attached to a chain from some tricky pool that are in the future (this happens if their clock is ahead of the actual time). I decided not to change the code because future blocks are something that should be noticed, investigated, and reported.

Closing this as "won't fix". Feel free to reopen/debate, I welcome constructive feedback.

**Closed by gacallea** 2020-05-22 11:01 UTC

**Comment by node-networks-crypto** [comment] 2020-05-22 20:52
You're welcome for the feedback.

I didn't do a wholistic review of all the conditions such as what you've outlined so thanks for the details!
